import type { Metadata } from 'next';
import './globals.css';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/app/theme/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en" dir="rtl">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <body>
            <main>{children}</main>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
};

export default RootLayout;
